In [104]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [105]:
braz_url = "https://brazil-help.com/brazilian_states.htm"

response_braz = requests.get(braz_url)

soup_braz = BeautifulSoup(response_braz.content, 'html.parser')

In [133]:
print(soup_braz.prettify)

In [107]:
soup_braz.find_all(class_="MsoNormalTable")[2].find_all("tr")[1].find_all("td")[0].find("center").get_text()

'Common\nTwo Letter\nAbbreviation'

In [108]:
list1 = [None] * 10 

for x in range(10):
  list1[x] = list()

for i in range(29):
  for y in range(10):
    list1[y].append(
        soup_braz.find_all(class_="MsoNormalTable")[2].find_all("tr")[i].find_all("td")[y].find("center").get_text()
    )

for a in range(10):
  print(list1[a])

['BR', 'Common\nTwo Letter\nAbbreviation', 'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
['Brazil\n(entire country)', 'State', 'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito\nFederal', 'Espírito\nSanto', 'Goiás', 'Maranhão', 'MatoGrosso', 'MatoGrosso\ndo Sul', 'Minas\nGerais', 'Pará', 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio\nde Janeiro', 'Rio\nGrande do Norte', 'Rio\nGrande do Sul', 'Rondônia', 'Roraima', 'Santa\nCatarina', 'São\nPaulo', 'Sergipe', 'Tocantins']
['Brasília', 'Capitol\nCity', 'Rio Branco', 'Maceió', 'Macapá', 'Manaus', 'Salvador', 'Fortaleza', 'Brasília', 'Vitória', 'Goiânia', 'São\nLuís', 'Cuiabá', 'Campo Grande', 'Belo Horizonte', 'Belém', 'João\nPessoa', 'Curitiba', 'Recife', 'Teresina', 'Rio de Janeiro', 'Natal', 'Porto Alegre', 'Porto Velho', 'Boa Vista', 'Florianópolis', 'São\nPaulo', 'Aracajú', 'Palmas']
['-', 'Region', 'North', 'Northeast', 'North', 'North', 'Northeast', 'Northeast', 'Center\nWest', 'Southeast', 'Center\nWest', 'Northeast', 'Center\nWest', 'Center\nWest', 'Southeast', 'North', 'Northeast', 'South', 'Northeast', 'Northeast', 'Southeast', 'Northeast', 'South', 'North', 'North', 'South', 'Southeast', 'Northeast', 'North']
['8,514,204\n(slightly larger than\nthe Continental United States)', 'Size\n(in km²)', '152,581', '27,767', '142,814', '1,570,745', '564,692', '148,825', '5,801', '46,077', '340,086', '331,983', '903,357', '357,124', '586,528', '1,247,689', '56,440', '199,315', '98,311', '251,529', '43,696', '52,796', '281,748', '237,576', '224,298', '95,346', '248,209', '21,910', '277,620']
['192,000,000(2008\nestimate)', 'Population\n(2007 estimate)', '664,000', '3,557,000', '619,000', '3,351,000', '13,974,000', '8,238,000', '2,393,000', '3,474,000', '5,750,000', '6,199,000', '2,866,000', '2,304,000', '19,522,000', '7,136,000', '3,595,886', '10,261,856', '8,518,000', '3,041,000', '15,593,000', '3,051,000', '10,984,000', '1,567,000', '405,000', '5,974,000', '41,164,000', '2,007,000', '1,337,000']
['82.5/17.5', '%\nPop.\nUrban/Rural', '69.6/30.4', '67.4/32.6', '93.7/6.3', '77.6/22.4', '67.4/32.6', '76.4/23.6', '94/6', '82.2/17.8', '88.6/11.4', '67/33', '76.6/23.4', '84.7/15.3', '84.7/15.3', '75.2/24.8', '75.8/24.2', '83.6/16.4', '76.8/23.2', '60.7/39.3', '96.9/3.1', '72.4/27.6', '801.5/18.5', '68.2/31.8', '81.6/17.7', '82.5/17.5', '94.5/5.5', '82.2/17.8', '74.1/25.9']
['5,564', 'Number\nof Municipal Districts', '24', '102', '16', '62', '417', '184', '1', '78', '246', '217', '141', '78', '853', '143', '223', '399', '185', '223', '92', '167', '496', '52', '15', '293', '645', '75', '139']
['R$8,300', 'Per\nCapita GNP in Reais (R$)', 'R$5,413', 'R$3,876', 'R$6,796', 'R$11,434', 'R$6,350', 'R$4,169', 'R$19,071', 'R$10,288', 'R$7,500', 'R$2,748', 'R$10,161', 'R$8,944', 'R$8,770', 'R$4,991', 'R$3,872', 'R$9,891', 'R$5,730', 'R$2,892', 'R$14,638', 'R$5,369', 'R$ 13,320', 'R$6,238', 'R$4,881', 'R$12,158', 'R$13,725', 'R$6,782', 'R$3,776']
['72.24', 'Life\nExpectancy\n(2007 projection)', '71.1', '65.4', '70.1', '71.3', '71.7', '69.9', '75.1', '73.4', '73.1', '67.2', '72.9', '73.5', '74.4', '71.7', '67.9', '73.2', '67.9', '68.8', '72.8', '70.1', '74.8', '70.9', '69.6', '75', '73.9', '70.6', '71']

In [134]:
dict1 = {}
for x in range(10):
  if x == 0:
    a = list1[x].pop(1)
    dict1.update({a: list1[x]})
  elif x == 1:
    b = list1[x].pop(1)
    dict1.update({b: list1[x]})
  elif x == 2:
    c = list1[x].pop(1)
    dict1.update({c: list1[x]})
  elif x == 3:
    d = list1[x].pop(1)
    dict1.update({d: list1[x]})
  elif x == 4:
    e = list1[x].pop(1)
    dict1.update({e: list1[x]})
  elif x == 5:
    f = list1[x].pop(1)
    dict1.update({f: list1[x]})
  elif x == 6:
    g = list1[x].pop(1)
    dict1.update({g: list1[x]})
  elif x == 7:
    h = list1[x].pop(1)
    dict1.update({h: list1[x]})
  elif x == 8:
    i = list1[x].pop(1)
    dict1.update({i: list1[x]})
  elif x == 9:
    j = list1[x].pop(1)
    dict1.update({j: list1[x]})




print(dict1)

In [110]:
for y in dict1:
    print(y, ":",dict1[y])

Common
Two Letter
Abbreviation : ['BR', 'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO']
State : ['Brazil\n(entire country)', 'Acre', 'Alagoas', 'Amapá', 'Amazonas', 'Bahia', 'Ceará', 'Distrito\nFederal', 'Espírito\nSanto', 'Goiás', 'Maranhão', 'MatoGrosso', 'MatoGrosso\ndo Sul', 'Minas\nGerais', 'Pará', 'Paraíba', 'Paraná', 'Pernambuco', 'Piauí', 'Rio\nde Janeiro', 'Rio\nGrande do Norte', 'Rio\nGrande do Sul', 'Rondônia', 'Roraima', 'Santa\nCatarina', 'São\nPaulo', 'Sergipe', 'Tocantins']
Capitol
City : ['Brasília', 'Rio Branco', 'Maceió', 'Macapá', 'Manaus', 'Salvador', 'Fortaleza', 'Brasília', 'Vitória', 'Goiânia', 'São\nLuís', 'Cuiabá', 'Campo Grande', 'Belo Horizonte', 'Belém', 'João\nPessoa', 'Curitiba', 'Recife', 'Teresina', 'Rio de Janeiro', 'Natal', 'Porto Alegre', 'Porto Velho', 'Boa Vista', 'Florianópolis', 'São\nPaulo', 'Aracajú', 'Palmas']
Region : ['-', 'North', 'Northeast', 'North', 'North', 'Northeast', 'Northeast', 'Center\nWest', 'Southeast', 'Center\nWest', 'Northeast', 'Center\nWest', 'Center\nWest', 'Southeast', 'North', 'Northeast', 'South', 'Northeast', 'Northeast', 'Southeast', 'Northeast', 'South', 'North', 'North', 'South', 'Southeast', 'Northeast', 'North']
Size
(in km²) : ['8,514,204\n(slightly larger than\nthe Continental United States)', '152,581', '27,767', '142,814', '1,570,745', '564,692', '148,825', '5,801', '46,077', '340,086', '331,983', '903,357', '357,124', '586,528', '1,247,689', '56,440', '199,315', '98,311', '251,529', '43,696', '52,796', '281,748', '237,576', '224,298', '95,346', '248,209', '21,910', '277,620']
Population
(2007 estimate) : ['192,000,000(2008\nestimate)', '664,000', '3,557,000', '619,000', '3,351,000', '13,974,000', '8,238,000', '2,393,000', '3,474,000', '5,750,000', '6,199,000', '2,866,000', '2,304,000', '19,522,000', '7,136,000', '3,595,886', '10,261,856', '8,518,000', '3,041,000', '15,593,000', '3,051,000', '10,984,000', '1,567,000', '405,000', '5,974,000', '41,164,000', '2,007,000', '1,337,000']
%
Pop.
Urban/Rural : ['82.5/17.5', '69.6/30.4', '67.4/32.6', '93.7/6.3', '77.6/22.4', '67.4/32.6', '76.4/23.6', '94/6', '82.2/17.8', '88.6/11.4', '67/33', '76.6/23.4', '84.7/15.3', '84.7/15.3', '75.2/24.8', '75.8/24.2', '83.6/16.4', '76.8/23.2', '60.7/39.3', '96.9/3.1', '72.4/27.6', '801.5/18.5', '68.2/31.8', '81.6/17.7', '82.5/17.5', '94.5/5.5', '82.2/17.8', '74.1/25.9']
Number
of Municipal Districts : ['5,564', '24', '102', '16', '62', '417', '184', '1', '78', '246', '217', '141', '78', '853', '143', '223', '399', '185', '223', '92', '167', '496', '52', '15', '293', '645', '75', '139']
Per
Capita GNP in Reais (R$) : ['R$8,300', 'R$5,413', 'R$3,876', 'R$6,796', 'R$11,434', 'R$6,350', 'R$4,169', 'R$19,071', 'R$10,288', 'R$7,500', 'R$2,748', 'R$10,161', 'R$8,944', 'R$8,770', 'R$4,991', 'R$3,872', 'R$9,891', 'R$5,730', 'R$2,892', 'R$14,638', 'R$5,369', 'R$ 13,320', 'R$6,238', 'R$4,881', 'R$12,158', 'R$13,725', 'R$6,782', 'R$3,776']
Life
Expectancy
(2007 projection) : ['72.24', '71.1', '65.4', '70.1', '71.3', '71.7', '69.9', '75.1', '73.4', '73.1', '67.2', '72.9', '73.5', '74.4', '71.7', '67.9', '73.2', '67.9', '68.8', '72.8', '70.1', '74.8', '70.9', '69.6', '75', '73.9', '70.6', '71']

In [111]:
braz_df = pd.DataFrame(dict1)

In [135]:
braz_df.info()

In [113]:
braz_df

,Common\nTwo Letter\nAbbreviation,State,Capitol\nCity,Region,Size\n(in km²),Population\n(2007 estimate),%\nPop.\nUrban/Rural,Number\nof Municipal Districts,Per\nCapita GNP in Reais (R$),Life\nExpectancy\n(2007 projection)
0,BR,Brazil\n(entire country),Brasília,-,"8,514,204\n(slightly larger than\nthe Continen...","192,000,000(2008\nestimate)",82.5/17.5,"5,564","R$8,300",72.24
1,AC,Acre,Rio Branco,North,"152,581","664,000",69.6/30.4,24,"R$5,413",71.1
2,AL,Alagoas,Maceió,Northeast,"27,767","3,557,000",67.4/32.6,102,"R$3,876",65.4
3,AP,Amapá,Macapá,North,"142,814","619,000",93.7/6.3,16,"R$6,796",70.1
4,AM,Amazonas,Manaus,North,"1,570,745","3,351,000",77.6/22.4,62,"R$11,434",71.3
5,BA,Bahia,Salvador,Northeast,"564,692","13,974,000",67.4/32.6,417,"R$6,350",71.7
6,CE,Ceará,Fortaleza,Northeast,"148,825","8,238,000",76.4/23.6,184,"R$4,169",69.9
7,DF,Distrito\nFederal,Brasília,Center\nWest,"5,801","2,393,000",94/6,1,"R$19,071",75.1
8,ES,Espírito\nSanto,Vitória,Southeast,"46,077","3,474,000",82.2/17.8,78,"R$10,288",73.4
9,GO,Goiás,Goiânia,Center\nWest,"340,086","5,750,000",88.6/11.4,246,"R$7,500",73.1
10,MA,Maranhão,São\nLuís,Northeast,"331,983","6,199,000",67/33,217,"R$2,748",67.2
11,MT,MatoGrosso,Cuiabá,Center\nWest,"903,357","2,866,000",76.6/23.4,141,"R$10,161",72.9
12,MS,MatoGrosso\ndo Sul,Campo Grande,Center\nWest,"357,124","2,304,000",84.7/15.3,78,"R$8,944",73.5
13,MG,Minas\nGerais,Belo Horizonte,Southeast,"586,528","19,522,000",84.7/15.3,853,"R$8,770",74.4
14,PA,Pará,Belém,North,"1,247,689","7,136,000",75.2/24.8,143,"R$4,991",71.7
15,PB,Paraíba,João\nPessoa,Northeast,"56,440","3,595,886",75.8/24.2,223,"R$3,872",67.9
16,PR,Paraná,Curitiba,South,"199,315","10,261,856",83.6/16.4,399,"R$9,891",73.2
17,PE,Pernambuco,Recife,Northeast,"98,311","8,518,000",76.8/23.2,185,"R$5,730",67.9
18,PI,Piauí,Teresina,Northeast,"251,529","3,041,000",60.7/39.3,223,"R$2,892",68.8
19,RJ,Rio\nde Janeiro,Rio de Janeiro,Southeast,"43,696","15,593,000",96.9/3.1,92,"R$14,638",72.8
20,RN,Rio\nGrande do Norte,Natal,Northeast,"52,796","3,051,000",72.4/27.6,167,"R$5,369",70.1
21,RS,Rio\nGrande do Sul,Porto Alegre,South,"281,748","10,984,000",801.5/18.5,496,"R$ 13,320",74.8
22,RO,Rondônia,Porto Velho,North,"237,576","1,567,000",68.2/31.8,52,"R$6,238",70.9
23,RR,Roraima,Boa Vista,North,"224,298","405,000",81.6/17.7,15,"R$4,881",69.6
24,SC,Santa\nCatarina,Florianópolis,South,"95,346","5,974,000",82.5/17.5,293,"R$12,158",75
25,SP,São\nPaulo,São\nPaulo,Southeast,"248,209","41,164,000",94.5/5.5,645,"R$13,725",73.9
26,SE,Sergipe,Aracajú,Northeast,"21,910","2,007,000",82.2/17.8,75,"R$6,782",70.6
27,TO,Tocantins,Palmas,North,"277,620","1,337,000",74.1/25.9,139,"R$3,776",71

In [114]:
braz_df2 = braz_df.copy()

In [136]:
listd = []
for t in dict1:
    listd.append(t)

In [116]:
listd

['Common\nTwo Letter\nAbbreviation',
 'State',
 'Capitol\nCity',
 'Region',
 'Size\n(in km²)',
 'Population\n(2007 estimate)',
 '%\nPop.\nUrban/Rural',
 'Number\nof Municipal Districts',
 'Per\nCapita GNP in Reais (R$)',
 'Life\nExpectancy\n(2007 projection)']

In [117]:
listd2 = listd.copy()

In [118]:
import re

In [119]:
# for l in range(len(listd)):
#     listd2[l] = listd2[l].replace("\n", " ")

for l in range(len(listd)):
    listd2[l] = listd2[l].replace("\n", "_")
    listd2[l] = listd2[l].replace("(", "")
    listd2[l] = listd2[l].replace(")", "")
    listd2[l] = listd2[l].replace(" ", "_")

In [120]:
listd2

['Common_Two_Letter_Abbreviation',
 'State',
 'Capitol_City',
 'Region',
 'Size_in_km²',
 'Population_2007_estimate',
 '%_Pop._Urban/Rural',
 'Number_of_Municipal_Districts',
 'Per_Capita_GNP_in_Reais_R$',
 'Life_Expectancy_2007_projection']

In [121]:
dict2 = {}
for x in range(10):
  if x == 0:
    dict2.update({listd[x]: listd2[x]})
  elif x == 2:
    dict2.update({listd[x]: listd2[x]})
  elif x == 2:
    dict2.update({listd[x]: listd2[x]})
  elif x == 3:
    dict2.update({listd[x]: listd2[x]})
  elif x == 4:
    dict2.update({listd[x]: listd2[x]})
  elif x == 5:
    dict2.update({listd[x]: listd2[x]})
  elif x == 6:
    dict2.update({listd[x]: listd2[x]})
  elif x == 7:
    dict2.update({listd[x]: listd2[x]})
  elif x == 8:
    dict2.update({listd[x]: listd2[x]})
  elif x == 9:
    dict2.update({listd[x]: listd2[x]})

In [122]:
dict2

{'Common\nTwo Letter\nAbbreviation': 'Common_Two_Letter_Abbreviation',
 'Capitol\nCity': 'Capitol_City',
 'Region': 'Region',
 'Size\n(in km²)': 'Size_in_km²',
 'Population\n(2007 estimate)': 'Population_2007_estimate',
 '%\nPop.\nUrban/Rural': '%_Pop._Urban/Rural',
 'Number\nof Municipal Districts': 'Number_of_Municipal_Districts',
 'Per\nCapita GNP in Reais (R$)': 'Per_Capita_GNP_in_Reais_R$',
 'Life\nExpectancy\n(2007 projection)': 'Life_Expectancy_2007_projection'}

In [123]:
braz_df2 = braz_df2.rename( columns = dict2)

In [124]:
braz_df2

,Common_Two_Letter_Abbreviation,State,Capitol_City,Region,Size_in_km²,Population_2007_estimate,%_Pop._Urban/Rural,Number_of_Municipal_Districts,Per_Capita_GNP_in_Reais_R$,Life_Expectancy_2007_projection
0,BR,Brazil\n(entire country),Brasília,-,"8,514,204\n(slightly larger than\nthe Continen...","192,000,000(2008\nestimate)",82.5/17.5,"5,564","R$8,300",72.24
1,AC,Acre,Rio Branco,North,"152,581","664,000",69.6/30.4,24,"R$5,413",71.1
2,AL,Alagoas,Maceió,Northeast,"27,767","3,557,000",67.4/32.6,102,"R$3,876",65.4
3,AP,Amapá,Macapá,North,"142,814","619,000",93.7/6.3,16,"R$6,796",70.1
4,AM,Amazonas,Manaus,North,"1,570,745","3,351,000",77.6/22.4,62,"R$11,434",71.3
5,BA,Bahia,Salvador,Northeast,"564,692","13,974,000",67.4/32.6,417,"R$6,350",71.7
6,CE,Ceará,Fortaleza,Northeast,"148,825","8,238,000",76.4/23.6,184,"R$4,169",69.9
7,DF,Distrito\nFederal,Brasília,Center\nWest,"5,801","2,393,000",94/6,1,"R$19,071",75.1
8,ES,Espírito\nSanto,Vitória,Southeast,"46,077","3,474,000",82.2/17.8,78,"R$10,288",73.4
9,GO,Goiás,Goiânia,Center\nWest,"340,086","5,750,000",88.6/11.4,246,"R$7,500",73.1
10,MA,Maranhão,São\nLuís,Northeast,"331,983","6,199,000",67/33,217,"R$2,748",67.2
11,MT,MatoGrosso,Cuiabá,Center\nWest,"903,357","2,866,000",76.6/23.4,141,"R$10,161",72.9
12,MS,MatoGrosso\ndo Sul,Campo Grande,Center\nWest,"357,124","2,304,000",84.7/15.3,78,"R$8,944",73.5
13,MG,Minas\nGerais,Belo Horizonte,Southeast,"586,528","19,522,000",84.7/15.3,853,"R$8,770",74.4
14,PA,Pará,Belém,North,"1,247,689","7,136,000",75.2/24.8,143,"R$4,991",71.7
15,PB,Paraíba,João\nPessoa,Northeast,"56,440","3,595,886",75.8/24.2,223,"R$3,872",67.9
16,PR,Paraná,Curitiba,South,"199,315","10,261,856",83.6/16.4,399,"R$9,891",73.2
17,PE,Pernambuco,Recife,Northeast,"98,311","8,518,000",76.8/23.2,185,"R$5,730",67.9
18,PI,Piauí,Teresina,Northeast,"251,529","3,041,000",60.7/39.3,223,"R$2,892",68.8
19,RJ,Rio\nde Janeiro,Rio de Janeiro,Southeast,"43,696","15,593,000",96.9/3.1,92,"R$14,638",72.8
20,RN,Rio\nGrande do Norte,Natal,Northeast,"52,796","3,051,000",72.4/27.6,167,"R$5,369",70.1
21,RS,Rio\nGrande do Sul,Porto Alegre,South,"281,748","10,984,000",801.5/18.5,496,"R$ 13,320",74.8
22,RO,Rondônia,Porto Velho,North,"237,576","1,567,000",68.2/31.8,52,"R$6,238",70.9
23,RR,Roraima,Boa Vista,North,"224,298","405,000",81.6/17.7,15,"R$4,881",69.6
24,SC,Santa\nCatarina,Florianópolis,South,"95,346","5,974,000",82.5/17.5,293,"R$12,158",75
25,SP,São\nPaulo,São\nPaulo,Southeast,"248,209","41,164,000",94.5/5.5,645,"R$13,725",73.9
26,SE,Sergipe,Aracajú,Northeast,"21,910","2,007,000",82.2/17.8,75,"R$6,782",70.6
27,TO,Tocantins,Palmas,North,"277,620","1,337,000",74.1/25.9,139,"R$3,776",71

In [125]:
for g in range(len(listd2)):
  braz_df2[listd2[g]] = braz_df2[listd2[g]].str.replace("\n", " ")

In [126]:
braz_df2

,Common_Two_Letter_Abbreviation,State,Capitol_City,Region,Size_in_km²,Population_2007_estimate,%_Pop._Urban/Rural,Number_of_Municipal_Districts,Per_Capita_GNP_in_Reais_R$,Life_Expectancy_2007_projection
0,BR,Brazil (entire country),Brasília,-,"8,514,204 (slightly larger than the Continenta...","192,000,000(2008 estimate)",82.5/17.5,"5,564","R$8,300",72.24
1,AC,Acre,Rio Branco,North,"152,581","664,000",69.6/30.4,24,"R$5,413",71.1
2,AL,Alagoas,Maceió,Northeast,"27,767","3,557,000",67.4/32.6,102,"R$3,876",65.4
3,AP,Amapá,Macapá,North,"142,814","619,000",93.7/6.3,16,"R$6,796",70.1
4,AM,Amazonas,Manaus,North,"1,570,745","3,351,000",77.6/22.4,62,"R$11,434",71.3
5,BA,Bahia,Salvador,Northeast,"564,692","13,974,000",67.4/32.6,417,"R$6,350",71.7
6,CE,Ceará,Fortaleza,Northeast,"148,825","8,238,000",76.4/23.6,184,"R$4,169",69.9
7,DF,Distrito Federal,Brasília,Center West,"5,801","2,393,000",94/6,1,"R$19,071",75.1
8,ES,Espírito Santo,Vitória,Southeast,"46,077","3,474,000",82.2/17.8,78,"R$10,288",73.4
9,GO,Goiás,Goiânia,Center West,"340,086","5,750,000",88.6/11.4,246,"R$7,500",73.1
10,MA,Maranhão,São Luís,Northeast,"331,983","6,199,000",67/33,217,"R$2,748",67.2
11,MT,MatoGrosso,Cuiabá,Center West,"903,357","2,866,000",76.6/23.4,141,"R$10,161",72.9
12,MS,MatoGrosso do Sul,Campo Grande,Center West,"357,124","2,304,000",84.7/15.3,78,"R$8,944",73.5
13,MG,Minas Gerais,Belo Horizonte,Southeast,"586,528","19,522,000",84.7/15.3,853,"R$8,770",74.4
14,PA,Pará,Belém,North,"1,247,689","7,136,000",75.2/24.8,143,"R$4,991",71.7
15,PB,Paraíba,João Pessoa,Northeast,"56,440","3,595,886",75.8/24.2,223,"R$3,872",67.9
16,PR,Paraná,Curitiba,South,"199,315","10,261,856",83.6/16.4,399,"R$9,891",73.2
17,PE,Pernambuco,Recife,Northeast,"98,311","8,518,000",76.8/23.2,185,"R$5,730",67.9
18,PI,Piauí,Teresina,Northeast,"251,529","3,041,000",60.7/39.3,223,"R$2,892",68.8
19,RJ,Rio de Janeiro,Rio de Janeiro,Southeast,"43,696","15,593,000",96.9/3.1,92,"R$14,638",72.8
20,RN,Rio Grande do Norte,Natal,Northeast,"52,796","3,051,000",72.4/27.6,167,"R$5,369",70.1
21,RS,Rio Grande do Sul,Porto Alegre,South,"281,748","10,984,000",801.5/18.5,496,"R$ 13,320",74.8
22,RO,Rondônia,Porto Velho,North,"237,576","1,567,000",68.2/31.8,52,"R$6,238",70.9
23,RR,Roraima,Boa Vista,North,"224,298","405,000",81.6/17.7,15,"R$4,881",69.6
24,SC,Santa Catarina,Florianópolis,South,"95,346","5,974,000",82.5/17.5,293,"R$12,158",75
25,SP,São Paulo,São Paulo,Southeast,"248,209","41,164,000",94.5/5.5,645,"R$13,725",73.9
26,SE,Sergipe,Aracajú,Northeast,"21,910","2,007,000",82.2/17.8,75,"R$6,782",70.6
27,TO,Tocantins,Palmas,North,"277,620","1,337,000",74.1/25.9,139,"R$3,776",71

In [127]:
braz_sql_df = braz_df2.copy()

In [128]:
# dict3 = {}
# for x in range(10):
#   if x == 0:
#     dict3.update({listd2[x]: "Common_Two_Letter_Abbreviation"})
#   elif x == 1:
#     continue
#   elif x == 2:
#     dict3.update({listd2[x]: "Capital_City"})
#   elif x == 3:
#     continue
#   elif x == 4:
#     dict3.update({listd2[x]: "Size_km_squared"})
#   elif x == 5:
#     dict3.update({listd2[x]: "Population_2007_estimate"})
#   elif x == 6:
#     dict3.update({listd2[x]: "Pop_percent_Urban_Rural"})
#   elif x == 7:
#     dict3.update({listd2[x]: "Number_of_Municipal_Districts"})
#   elif x == 8:
#     dict3.update({listd2[x]: "Per_Capita_GNP_in_Reais_R$"})
#   elif x == 9:
#     dict3.update({listd2[x]: "Life_Expectancy_2007_projection"})

In [129]:
# braz_sql_df = braz_sql_df.rename( columns = dict3)

In [130]:
braz_sql_df

,Common_Two_Letter_Abbreviation,State,Capitol_City,Region,Size_in_km²,Population_2007_estimate,%_Pop._Urban/Rural,Number_of_Municipal_Districts,Per_Capita_GNP_in_Reais_R$,Life_Expectancy_2007_projection
0,BR,Brazil (entire country),Brasília,-,"8,514,204 (slightly larger than the Continenta...","192,000,000(2008 estimate)",82.5/17.5,"5,564","R$8,300",72.24
1,AC,Acre,Rio Branco,North,"152,581","664,000",69.6/30.4,24,"R$5,413",71.1
2,AL,Alagoas,Maceió,Northeast,"27,767","3,557,000",67.4/32.6,102,"R$3,876",65.4
3,AP,Amapá,Macapá,North,"142,814","619,000",93.7/6.3,16,"R$6,796",70.1
4,AM,Amazonas,Manaus,North,"1,570,745","3,351,000",77.6/22.4,62,"R$11,434",71.3
5,BA,Bahia,Salvador,Northeast,"564,692","13,974,000",67.4/32.6,417,"R$6,350",71.7
6,CE,Ceará,Fortaleza,Northeast,"148,825","8,238,000",76.4/23.6,184,"R$4,169",69.9
7,DF,Distrito Federal,Brasília,Center West,"5,801","2,393,000",94/6,1,"R$19,071",75.1
8,ES,Espírito Santo,Vitória,Southeast,"46,077","3,474,000",82.2/17.8,78,"R$10,288",73.4
9,GO,Goiás,Goiânia,Center West,"340,086","5,750,000",88.6/11.4,246,"R$7,500",73.1
10,MA,Maranhão,São Luís,Northeast,"331,983","6,199,000",67/33,217,"R$2,748",67.2
11,MT,MatoGrosso,Cuiabá,Center West,"903,357","2,866,000",76.6/23.4,141,"R$10,161",72.9
12,MS,MatoGrosso do Sul,Campo Grande,Center West,"357,124","2,304,000",84.7/15.3,78,"R$8,944",73.5
13,MG,Minas Gerais,Belo Horizonte,Southeast,"586,528","19,522,000",84.7/15.3,853,"R$8,770",74.4
14,PA,Pará,Belém,North,"1,247,689","7,136,000",75.2/24.8,143,"R$4,991",71.7
15,PB,Paraíba,João Pessoa,Northeast,"56,440","3,595,886",75.8/24.2,223,"R$3,872",67.9
16,PR,Paraná,Curitiba,South,"199,315","10,261,856",83.6/16.4,399,"R$9,891",73.2
17,PE,Pernambuco,Recife,Northeast,"98,311","8,518,000",76.8/23.2,185,"R$5,730",67.9
18,PI,Piauí,Teresina,Northeast,"251,529","3,041,000",60.7/39.3,223,"R$2,892",68.8
19,RJ,Rio de Janeiro,Rio de Janeiro,Southeast,"43,696","15,593,000",96.9/3.1,92,"R$14,638",72.8
20,RN,Rio Grande do Norte,Natal,Northeast,"52,796","3,051,000",72.4/27.6,167,"R$5,369",70.1
21,RS,Rio Grande do Sul,Porto Alegre,South,"281,748","10,984,000",801.5/18.5,496,"R$ 13,320",74.8
22,RO,Rondônia,Porto Velho,North,"237,576","1,567,000",68.2/31.8,52,"R$6,238",70.9
23,RR,Roraima,Boa Vista,North,"224,298","405,000",81.6/17.7,15,"R$4,881",69.6
24,SC,Santa Catarina,Florianópolis,South,"95,346","5,974,000",82.5/17.5,293,"R$12,158",75
25,SP,São Paulo,São Paulo,Southeast,"248,209","41,164,000",94.5/5.5,645,"R$13,725",73.9
26,SE,Sergipe,Aracajú,Northeast,"21,910","2,007,000",82.2/17.8,75,"R$6,782",70.6
27,TO,Tocantins,Palmas,North,"277,620","1,337,000",74.1/25.9,139,"R$3,776",71

In [131]:
for g in range(len(listd2)):
  if g == 4:
    braz_sql_df[listd2[g]] = braz_sql_df[listd2[g]].str.replace(",", "")
  elif g == 5:
    braz_sql_df[listd2[g]] = braz_sql_df[listd2[g]].str.replace(",", "")
  elif g == 8:
    braz_sql_df[listd2[g]] = braz_sql_df[listd2[g]].str.replace(",", "")
    braz_sql_df[listd2[g]] = braz_sql_df[listd2[g]].str.replace("R$", "")

In [132]:
braz_sql_df

,Common_Two_Letter_Abbreviation,State,Capitol_City,Region,Size_in_km²,Population_2007_estimate,%_Pop._Urban/Rural,Number_of_Municipal_Districts,Per_Capita_GNP_in_Reais_R$,Life_Expectancy_2007_projection
0,BR,Brazil (entire country),Brasília,-,8514204 (slightly larger than the Continental ...,192000000(2008 estimate),82.5/17.5,"5,564",8300,72.24
1,AC,Acre,Rio Branco,North,152581,664000,69.6/30.4,24,5413,71.1
2,AL,Alagoas,Maceió,Northeast,27767,3557000,67.4/32.6,102,3876,65.4
3,AP,Amapá,Macapá,North,142814,619000,93.7/6.3,16,6796,70.1
4,AM,Amazonas,Manaus,North,1570745,3351000,77.6/22.4,62,11434,71.3
5,BA,Bahia,Salvador,Northeast,564692,13974000,67.4/32.6,417,6350,71.7
6,CE,Ceará,Fortaleza,Northeast,148825,8238000,76.4/23.6,184,4169,69.9
7,DF,Distrito Federal,Brasília,Center West,5801,2393000,94/6,1,19071,75.1
8,ES,Espírito Santo,Vitória,Southeast,46077,3474000,82.2/17.8,78,10288,73.4
9,GO,Goiás,Goiânia,Center West,340086,5750000,88.6/11.4,246,7500,73.1
10,MA,Maranhão,São Luís,Northeast,331983,6199000,67/33,217,2748,67.2
11,MT,MatoGrosso,Cuiabá,Center West,903357,2866000,76.6/23.4,141,10161,72.9
12,MS,MatoGrosso do Sul,Campo Grande,Center West,357124,2304000,84.7/15.3,78,8944,73.5
13,MG,Minas Gerais,Belo Horizonte,Southeast,586528,19522000,84.7/15.3,853,8770,74.4
14,PA,Pará,Belém,North,1247689,7136000,75.2/24.8,143,4991,71.7
15,PB,Paraíba,João Pessoa,Northeast,56440,3595886,75.8/24.2,223,3872,67.9
16,PR,Paraná,Curitiba,South,199315,10261856,83.6/16.4,399,9891,73.2
17,PE,Pernambuco,Recife,Northeast,98311,8518000,76.8/23.2,185,5730,67.9
18,PI,Piauí,Teresina,Northeast,251529,3041000,60.7/39.3,223,2892,68.8
19,RJ,Rio de Janeiro,Rio de Janeiro,Southeast,43696,15593000,96.9/3.1,92,14638,72.8
20,RN,Rio Grande do Norte,Natal,Northeast,52796,3051000,72.4/27.6,167,5369,70.1
21,RS,Rio Grande do Sul,Porto Alegre,South,281748,10984000,801.5/18.5,496,13320,74.8
22,RO,Rondônia,Porto Velho,North,237576,1567000,68.2/31.8,52,6238,70.9
23,RR,Roraima,Boa Vista,North,224298,405000,81.6/17.7,15,4881,69.6
24,SC,Santa Catarina,Florianópolis,South,95346,5974000,82.5/17.5,293,12158,75
25,SP,São Paulo,São Paulo,Southeast,248209,41164000,94.5/5.5,645,13725,73.9
26,SE,Sergipe,Aracajú,Northeast,21910,2007000,82.2/17.8,75,6782,70.6
27,TO,Tocantins,Palmas,North,277620,1337000,74.1/25.9,139,3776,71

In [86]:
schema = "magist"
host = "127.0.0.1"
user = "root"
password = ""
port = 3306

connection_string = f'mysql+pymysql://{user}:{password}@{host}:{port}/{schema}'

In [133]:
braz_sql_df.to_sql("brazil_states", if_exists="append", con = connection_string, index=False)

28

In [134]:
# df_from_sql = pd.read_sql("brazil_states", con=connection_string)
# df_from_sql